/* imgtogba version 1.0 */

#include <stdio.h>
#include <stdlib.h>

#include "include/gd.h"

#define VARNAME argv[1]
#define FILENAME argv[2]

/* Lookup table for:
 * (int) round((double) x * (31.0 / 255.0))
 * from 0-255 */
extern const int lookup[];

int rgb_conv(int r, int g, int b, int is_tcolor)
{

    r = lookup[r];
    g = lookup[g];
    b = lookup[b];
    return r | (g << 5) | (b << 10) | (is_tcolor << 15);
}

int valid_varname(char *s)
{
    if (!*s || isdigit(*s))
        return 0;
    while (*s) {
        if (!isalpha(*s) && !isdigit(*s) && *s != '_')
            return 0;
        s++;
    }
    return 1;
}

int main(int argc, char *argv[])
{
    if (argc < 3) {
        fprintf(stderr,
            "imgtogba: Converts a GIF/PNG/JPG to a C array for use with the GBA\n"
            "in the format: { [x dimension], [y dimension], [...data...] }\n\n"
            "Usage:\n"
            "imgtogba [var name] [img name] [[1/0] compact mode] [[1/0] transparent mode]\n"
            );
        return -1;
    }

    if (!valid_varname(VARNAME)) {
        fprintf(stderr, "Invalid C varname %s\n", VARNAME);
        return -2;
    }

    FILE *imgdata;
    gdImagePtr img = NULL;
    char header[4];
    int w, h;
    int x, y;
    int i;
    int type, color, rgb;
    int compact_mode = 0, transparent_mode = 0;
    if (argc > 3)
        compact_mode = atoi(argv[3]);
    if (argc > 4)
        transparent_mode = atoi(argv[4]);
    int tcolor;
    int is_tcolor;

    imgdata = fopen(FILENAME, "rb");

    if (!imgdata) {
        fprintf(stderr, "File %s read error: does not exist?\n", FILENAME);
        return -4;
    }

    for (i = 0; i < 4; ++i)
        header[i] = fgetc(imgdata);

    fclose(imgdata);
    imgdata = fopen(FILENAME, "rb");

    if (!imgdata) {
        fprintf(stderr, "File %s read error: does not exist?\n", FILENAME);
        return -4;
    }

    if (((header[0] & 0xFF) == 0xff) && ((header[1] & 0xFF) == 0xd8))
        img = gdImageCreateFromJpeg(imgdata);
    if (img)
        transparent_mode = 0;

    if (((header[0] & 0xFF) == 0x47) && ((header[1] & 0xFF) == 0x49)
        && ((header[2] & 0xFF) == 0x46))
        img = gdImageCreateFromGif(imgdata);

    if (((header[0] & 0xFF) == 0x89) && ((header[1] & 0xFF) == 0x50)
        && ((header[2] & 0xFF) == 0x4e) && ((header[3] & 0xFF) == 0x47)) {
        img = gdImageCreateFromPng(imgdata);
    }
    
    if (!img) {
        fprintf(stderr, "File %s read error: invalid image?\n", FILENAME);
        return -5;
    }

    fclose(imgdata);

    if (transparent_mode)
        tcolor = img->transparent;

    w = img->sx;
    h = img->sy;

    if (transparent_mode) {
        printf("/* 16-bit GBA transparent bitmap array generated by imgtogba */\n\n");
        printf("const unsigned short %s[] = {\n/* xdim  ydim, */\n", VARNAME);
        printf("   %4d, %4d", w, h);
        if (compact_mode == 1) {
            putchar('\n');
            for (y = i = 0; y < h; ++y) {
                for (x = 0; x < w; ++x) {
                    color = gdImageGetPixel(img, x, y);
                    is_tcolor = color == tcolor ? 1 : 0;
                    rgb = rgb_conv(
                            gdImageRed(img, color),
                            gdImageGreen(img, color),
                            gdImageBlue(img, color),
                            is_tcolor
                            );
                    printf(",%d", rgb);
                }
            }
            putchar('\n');
        } else {
            for (y = i = 0; y < h; ++y) {
                for (x = 0; x < w; ++x) {
                    color = gdImageGetPixel(img, x, y);
                    is_tcolor = color == tcolor ? 1 : 0;
                    rgb = rgb_conv(
                            gdImageRed(img, color),
                            gdImageGreen(img, color),
                            gdImageBlue(img, color),
                            is_tcolor
                            );
                    printf("%s0x%04x", (i++ % 10 ? ", " : ",\n"), rgb);
                }
            }
        }
    } else {
        if (img->trueColor && (header[0] & 0xFF) != 0x47) // Dither truecolor non-GIFs
            gdImageTrueColorToPalette(img, 1, 256);
        printf("/* 16-bit GBA bitmap array generated by imgtogba */\n\n");
        printf("const unsigned short %s[] = {\n/* xdim  ydim, */\n", VARNAME);
        printf("   %4d, %4d", w, h);
        if (compact_mode == 1) {
            putchar('\n');
            for (y = i = 0; y < h; ++y) {
                for (x = 0; x < w; ++x) {
                    color = gdImageGetPixel(img, x, y);
                    rgb = rgb_conv(
                            gdImageRed(img, color),
                            gdImageGreen(img, color),
                            gdImageBlue(img, color),
                            0
                            );
                    printf(",%d", rgb);
                }
            }
            putchar('\n');
        } else {
            for (y = i = 0; y < h; ++y) {
                for (x = 0; x < w; ++x) {
                    color = gdImageGetPixel(img, x, y);
                    rgb = rgb_conv(
                            gdImageRed(img, color),
                            gdImageGreen(img, color),
                            gdImageBlue(img, color),
                            0
                            );
                    printf("%s0x%04x", (i++ % 10 ? ", " : ",\n"), rgb);
                }
            }
        }
    }

    printf("};\n\n");
    gdImageDestroy(img);
    return 0;
}
